INSERT INTO USER (ID, NAME, PASSWORD, ROLES)
SELECT 1, 'csi_admin', '$2a$10$icb3hmalkIMvwS6UnmRgeeQH5GSL3ujwncEaKAr5x276w6OBxy7vy', 'aced0005757200135b4c6a6176612e6c616e672e537472696e673badd256e7e91d7b4702000078700000000174000541444d494e' FROM DUAL
WHERE NOT EXISTS (SELECT * FROM USER WHERE NAME='csi_admin');
INSERT INTO USER (ID, NAME, PASSWORD, ROLES)
SELECT 2, 'ccm_admin', '$2a$10$fv2XHFfsCqjZNdfFD1zwAu9nAD0HQaV11u47bX19gaWLqmAWi1vr.', 'aced0005757200135b4c6a6176612e6c616e672e537472696e673badd256e7e91d7b4702000078700000000174000541444d494e' FROM DUAL
WHERE NOT EXISTS (SELECT * FROM USER WHERE NAME='ccm_admin');

INSERT INTO COMPANY (ID, NAME)
SELECT 1, 'Cañete Structural Investigation Inc.' FROM DUAL
WHERE NOT EXISTS (SELECT * FROM COMPANY WHERE NAME = 'Cañete Structural Investigation Inc.');

INSERT INTO COMPANY (ID, NAME)
SELECT 2, 'CCM Network Manpower Solutions Inc.' FROM DUAL
WHERE NOT EXISTS (SELECT * FROM COMPANY WHERE NAME = 'CCM Network Manpower Solutions Inc.');

INSERT INTO EMPLOYEE (ID, FULL_NAME, COMPANY_ID, CREATED_DATE)
SELECT 1, 'KENNETH F. ESTALANE', 1, NOW() FROM DUAL WHERE NOT EXISTS (SELECT * FROM EMPLOYEE WHERE FULL_NAME='KENNETH F. ESTALANE');
INSERT INTO EMPLOYEE (ID, FULL_NAME, COMPANY_ID, CREATED_DATE)
SELECT 2, 'SAMUEL R. CHAN JR', 1, NOW() FROM DUAL WHERE NOT EXISTS (SELECT * FROM EMPLOYEE WHERE FULL_NAME='SAMUEL R. CHAN JR');
INSERT INTO EMPLOYEE (ID, FULL_NAME, COMPANY_ID, CREATED_DATE)
SELECT 3, 'KRIZZEL DAVID', 1, NOW() FROM DUAL WHERE NOT EXISTS (SELECT * FROM EMPLOYEE WHERE FULL_NAME='KRIZZEL DAVID');
INSERT INTO EMPLOYEE (ID, FULL_NAME, COMPANY_ID, CREATED_DATE)
SELECT 4, 'ALLEN PATRICK A. CANETE', 1, NOW() FROM DUAL WHERE NOT EXISTS (SELECT * FROM EMPLOYEE WHERE FULL_NAME='ALLEN PATRICK A. CANETE');
INSERT INTO EMPLOYEE (ID, FULL_NAME, COMPANY_ID, CREATED_DATE)
SELECT 5, 'RHODA A. VILLEGAS', 1, NOW() FROM DUAL WHERE NOT EXISTS (SELECT * FROM EMPLOYEE WHERE FULL_NAME='RHODA A. VILLEGAS');
INSERT INTO EMPLOYEE (ID, FULL_NAME, COMPANY_ID, CREATED_DATE)
SELECT 6, 'MICHAEL JAY B. MADALI', 1, NOW() FROM DUAL WHERE NOT EXISTS (SELECT * FROM EMPLOYEE WHERE FULL_NAME='MICHAEL JAY B. MADALI');
INSERT INTO EMPLOYEE (ID, FULL_NAME, COMPANY_ID, CREATED_DATE)
SELECT 7, 'GIL ANGELO J. DEL VALLE', 1, NOW() FROM DUAL WHERE NOT EXISTS (SELECT * FROM EMPLOYEE WHERE FULL_NAME='GIL ANGELO J. DEL VALLE');
INSERT INTO EMPLOYEE (ID, FULL_NAME, COMPANY_ID, CREATED_DATE)
SELECT 8, 'KENNETH D. SALVADOR', 1, NOW() FROM DUAL WHERE NOT EXISTS (SELECT * FROM EMPLOYEE WHERE FULL_NAME='KENNETH D. SALVADOR');
INSERT INTO EMPLOYEE (ID, FULL_NAME, COMPANY_ID, CREATED_DATE)
SELECT 9, 'ELMER V. AGABON', 1, NOW() FROM DUAL WHERE NOT EXISTS (SELECT * FROM EMPLOYEE WHERE FULL_NAME='ELMER V. AGABON');
INSERT INTO EMPLOYEE (ID, FULL_NAME, COMPANY_ID, CREATED_DATE)
SELECT 10, 'TRICIA ANNE C. OLIVEROS', 1, NOW() FROM DUAL WHERE NOT EXISTS (SELECT * FROM EMPLOYEE WHERE FULL_NAME='TRICIA ANNE C. OLIVEROS');
INSERT INTO EMPLOYEE (ID, FULL_NAME, COMPANY_ID, CREATED_DATE)
SELECT 11, 'MARKO ALLEN C. MACANAS', 1, NOW() FROM DUAL WHERE NOT EXISTS (SELECT * FROM EMPLOYEE WHERE FULL_NAME='MARKO ALLEN C. MACANAS');
INSERT INTO EMPLOYEE (ID, FULL_NAME, COMPANY_ID, CREATED_DATE)
SELECT 12, 'KENNETH M. ESPINO', 1, NOW() FROM DUAL WHERE NOT EXISTS (SELECT * FROM EMPLOYEE WHERE FULL_NAME='KENNETH M. ESPINO');
INSERT INTO EMPLOYEE (ID, FULL_NAME, COMPANY_ID, CREATED_DATE)
SELECT 13, 'MARK ANTHONY S. MENDOZA', 1, NOW() FROM DUAL WHERE NOT EXISTS (SELECT * FROM EMPLOYEE WHERE FULL_NAME='MARK ANTHONY S. MENDOZA');
INSERT INTO EMPLOYEE (ID, FULL_NAME, COMPANY_ID, CREATED_DATE)
SELECT 14, 'ROI E. DE JESUS', 1, NOW() FROM DUAL WHERE NOT EXISTS (SELECT * FROM EMPLOYEE WHERE FULL_NAME='ROI E. DE JESUS');
INSERT INTO EMPLOYEE (ID, FULL_NAME, COMPANY_ID, CREATED_DATE)
SELECT 15, 'PEEJAY T. TESORO', 1, NOW() FROM DUAL WHERE NOT EXISTS (SELECT * FROM EMPLOYEE WHERE FULL_NAME='PEEJAY T. TESORO');
INSERT INTO EMPLOYEE (ID, FULL_NAME, COMPANY_ID, CREATED_DATE)
SELECT 16, 'ALBERT PERRY A. CANETE', 1, NOW() FROM DUAL WHERE NOT EXISTS (SELECT * FROM EMPLOYEE WHERE FULL_NAME='ALBERT PERRY A. CANETE');
INSERT INTO EMPLOYEE (ID, FULL_NAME, COMPANY_ID, CREATED_DATE)
SELECT 17, 'REYNALDO TORRES', 1, NOW() FROM DUAL WHERE NOT EXISTS (SELECT * FROM EMPLOYEE WHERE FULL_NAME='REYNALDO TORRES');

INSERT INTO EMPLOYEE (ID, FULL_NAME, COMPANY_ID, CREATED_DATE)
SELECT 1000, 'Darwin Hiñosa', 2, NOW() FROM DUAL WHERE NOT EXISTS (SELECT * FROM EMPLOYEE WHERE FULL_NAME='Darwin Hiñosa');
INSERT INTO EMPLOYEE (ID, FULL_NAME, COMPANY_ID, CREATED_DATE)
SELECT 1001, 'Janessa Canonigo', 2, NOW() FROM DUAL WHERE NOT EXISTS (SELECT * FROM EMPLOYEE WHERE FULL_NAME='Janessa Canonigo');
INSERT INTO EMPLOYEE (ID, FULL_NAME, COMPANY_ID, CREATED_DATE)
SELECT 1002, 'Randolph Abary', 2, NOW() FROM DUAL WHERE NOT EXISTS (SELECT * FROM EMPLOYEE WHERE FULL_NAME='Randolph Abary');
INSERT INTO EMPLOYEE (ID, FULL_NAME, COMPANY_ID, CREATED_DATE)
SELECT 1003, 'Melvin Manansala', 2, NOW() FROM DUAL WHERE NOT EXISTS (SELECT * FROM EMPLOYEE WHERE FULL_NAME='Melvin Manansala');
INSERT INTO EMPLOYEE (ID, FULL_NAME, COMPANY_ID, CREATED_DATE)
SELECT 1004, 'Kelvin Chua', 2, NOW() FROM DUAL WHERE NOT EXISTS (SELECT * FROM EMPLOYEE WHERE FULL_NAME='Kelvin Chua');












