INSERT INTO COMPANY (ID, NAME)
SELECT 1, 'MY COMPANY' FROM DUAL WHERE NOT EXISTS (SELECT * FROM COMPANY);

INSERT INTO EMPLOYEE (ID, COMPANY_ID, FIRST_NAME, LAST_NAME)
SELECT 1, 1, 'Analyn', 'Flores' FROM DUAL WHERE NOT EXISTS (SELECT * FROM EMPLOYEE);

INSERT INTO HOLIDAY (ID, NAME, TYPE, HOLIDAY_DATE)
SELECT 1, 'Independence Day', 'Legal Holiday', '2018-06-12' FROM DUAL WHERE NOT EXISTS (SELECT * FROM HOLIDAY);