CREATE TABLE IF NOT EXISTS COMPANY
(
    ID INT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS EMPLOYEE
(
    ID INT PRIMARY KEY,
    COMPANY_ID INT,
    FULL_NAME VARCHAR(255),
    FINGERPRINT_ID VARCHAR(255),
    PIN VARCHAR(10),
    CREATED_DATE TIMESTAMP,
    FOREIGN KEY(COMPANY_ID) REFERENCES COMPANY(ID)
);

CREATE TABLE IF NOT EXISTS EMPLOYEE_TIME
(
    ID INT PRIMARY KEY,
    EMP_ID INT,
    TIME_IN TIMESTAMP,
    TIME_OUT TIMESTAMP,
    OVERTIME DOUBLE,
    UNDERTIME DOUBLE,
    CREATED_DATE TIMESTAMP,
    CREATED_BY VARCHAR(255),
    FOREIGN KEY(EMP_ID) REFERENCES EMPLOYEE(ID)
);

CREATE TABLE IF NOT EXISTS HOLIDAY
(
    ID INT PRIMARY KEY,
    NAME VARCHAR(255),
    TYPE VARCHAR(255),
    HOLIDAY_DATE DATE
);
